### ISSUE TITLE
chore: release checklist

### ISSUE THREAD

**Issue by mudler** [masa-finance/masa-bittensor#125]
As we are going to release bittensor to the public soon, we want to have a "release pre-flight checklist" that gives us a set of steps to follow in order to have a release.

For instance, an hypothetical checklist can be:

- [ ] Make sure CI tests are passing
- [ ] Check if there are any issue that are blockers to the release
- [ ] Make sure docker images are published correctly
- [ ] Tag the masa-bittensor release
- [ ] Do we have to handle pypi releases?
- [ ] Update the release note text
- [ ] Update the documentation website 
- [ ] Update installation instructions if needed https://github.com/masa-finance/masa-bittensor?tab=readme-ov-file#install
- [ ] Ping @giovaroma @lacyg4 

## Acceptance criteria
- [x] Define a release checklist, considering the above indications
- [x] Update the checklist in https://github.com/masa-finance/roadmap/blob/main/.github/ISSUE_TEMPLATE/release-bittensor.md
- [x] Update the checklist in https://github.com/masa-finance/roadmap/issues/1

**Comment by juanmanso** [comment]
From my understanding this task is blocked by the following (if true, then we could edit the description to show said blockers):
- Blocked by #85 
- Blocked by #111 
- Blocked by #109 
- [Optional] Blocked by #108

I've put the last one optional since we could go with the realise without static checks as linter for PRs.

**Comment by obasilakis** [comment]
>     * Blocked by [Github action to deploy devnet (opentensor subtensor instance with a subnet) #111](https://github.com/masa-finance/masa-bittensor/issues/111)

@juanmanso this isn't a blocker since the users will use the already deployed devnet.

**Comment by juanmanso** [comment]
> * Github action to deploy devnet (opentensor subtensor instance with a subnet) #111

@obasilakis I would agree but afaik the ticket was meant to tackle updates also. It could be avoided if deployment of any updates is handled automatically for the time being

**Comment by obasilakis** [comment]
- [ ] Restart devnet for clean state
- [ ] Remove local state for:
    - miner
    - validator
    - protocol node
- [ ] Follow instructions in [docs/setup](https://github.com/masa-finance/masa-bittensor/tree/main/docs/setup) to make sure everything is accurate and up-to-date

**Comment by juanmanso** [comment]
I'd say that the only thing remaining is the release notes.

Since development wasn't planned to be used as release notes (via PRs) maybe we can autogenerate it and then clean it up. Moreover, maybe we need to start it from scratch (hopefully not 🙏 )

**Comment by mudler** [comment]
> * [ ]  Restart devnet for clean state
> 
> * [ ]  Remove local state for:
>   
>   * miner
>   * validator
>   * protocol node


@obasilakis can you expand on these items? would anyone in the team be able to pick these items up by reading this check list ( spoiler: I can't )

**Comment by obasilakis** [comment]
@mudler I created this list before I knew about the competition. it's deprecated now.

**Comment by mudler** [comment]
ok I'm even more confused now - what is the checklist? does this needs to be worked on? are we good with the current checklist?

**Comment by Luka-Loncar** [comment]
@obasilakis can we get some clarity here before you go to your days off?

**Comment by giovaroma** [comment]
Overlaps with ticket #20 regarding the checklist. Ticket #20 to be updated as we have a more clear understanding. For now its under waterline and this ticket is a dependency.

**Comment by grantdfoster** [comment]
# Release Checklist

## Security
- [ ] Ensure dependencies are up to date and there are no known vulnerabilities.  Run `pip list --outdated` to see outdated dependencies.  If any dependencies need upgrading (and are in fact upgraded), run `pip freeze > requirements.txt` to update the requirements!

## Continuous Integration (CI)
- [ ] Ensure all CI tests are passing
  - [ ] Docker Build and Publish / check-and-build (subtensor)
  - [ ] Docker Build and Publish / check-and-build (subnet)
  - [ ] Docker Build and Publish / check-and-build (miner)
  - [ ] Docker Build and Publish / check-and-build (validator)
  - [ ] Docker Build and Publish / check-and-build (protocol)
  _it is possible that we will de-couple the protocol CI build and check in future iterations_

## Issue Tracking
- [ ] Verify there are no blockers to the release
_a typical release will [look like this](https://github.com/masa-finance/roadmap/issues/33), verify all issues are resolved!_

## Tagging
- [ ] Tag the `masa-bittensor` release, and ensure the latest tag is visible [here](https://github.com/masa-finance/masa-bittensor/tags)

## Release Notes
- [ ] Update release notes text.  An example of a previous release is [here](https://github.com/masa-finance/masa-bittensor/releases/tag/v0.5.0), built off of the `release.yml` configuration [here](https://github.com/masa-finance/masa-bittensor/blob/main/.github/release.yml)
- [ ] Ensure the latest release notes are captured [here](https://github.com/masa-finance/masa-bittensor/blob/main/docs/RELEASE_NOTES.md) so they automatically get published to our dev docs.

## Docker
- [ ] Confirm that Docker images are published correctly
_this was resolved in #160 and should work automatically!_

## Documentation
- [ ] Ensure documentation is updated.  This includes our setup documentation as well as advanced sections.  All markdown files [here](https://github.com/masa-finance/masa-bittensor/tree/main/docs) are automatically pushed to our developer docs website.  If certain documents do not appear, edit the sidebar [here](https://github.com/masa-finance/docs/blob/main/sidebars.js)
- [ ] Review and update installation instructions if needed: [Installation Guide](https://github.com/masa-finance/masa-bittensor?tab=readme-ov-file#install)

## Notifications
- [ ] Notify @giovaroma and @lacyg4.
