### ISSUE TITLE
AWS Devnet

### ISSUE THREAD

**Issue by Luka-Loncar** [masa-finance/masa-bittensor#2]
Set up development environment for Bittensor Subtensor Instance on AWS

The objective of this issue is to create a dedicated development environment on AWS to run a Bittensor subtensor instance for internal development and testing. This will involve setting up a local blockchain, often referred to as running on staging, which is isolated from the Bittensor mainchain and testchain.

### Tasks:

- [x]  **Provision AWS Infrastructure**
    - Set up AWS EC2 instances to host the subtensor nodes.
    - Configure security groups, IAM roles, and network settings to ensure secure and isolated access to the subtensor nodes.
- [x]  **Install Subtensor Dependencies**
    - Update system packages and install necessary libraries and tools as per the [[Running on Staging](https://github.com/opentensor/bittensor-subnet-template/blob/main/docs/running_on_staging.md)](https://github.com/opentensor/bittensor-subnet-template/blob/main/docs/running_on_staging.md) guide.
- [x]  **Install and Configure Rust**
    - Install Rust and Cargo using the provided script and configure the environment for Substrate development.
- [x]  **Clone Subtensor Repository**
    - Clone the subtensor repository to the EC2 instances and perform initial setup.
- [x]  **Build Subtensor Binary with Faucet Feature**
    - Compile the subtensor code with the faucet feature enabled to allow minting tokens for testing.
- [x]  **Initialize Local Subtensor Chain**
    - Run the localnet script to initialize the subtensor chain in development mode using the pow-fauct flag.
    
    `cargo build --release --features pow-faucet BUILD_BINARY=0 ./scripts/localnet.sh`

### Out of Scope

1. Setup wallets 
2. Installation of Bittensor Subnet 

### Acceptance Criteria:

- A fully functional local subtensor instance running on AWS capable of running a Bittensor subnet for development purposes.
- The chain must persist its state by ensuring the `—-base-path` is set to a directory

https://github.com/opentensor/subtensor/blob/571a4099b560b46eb9c96d7ac654241b52c7e5dc/scripts/localnet.sh#L33

- The subnet must be reachable through the following command for anyone on the development team to get testnet tTAO tokens.
`btcli wallet faucet --wallet.name owner --subtensor.chain_endpoint ws://127.0.0.1:9944`or ws://127.0.0.1:9945
- All necessary tools, dependencies, and configurations are installed and operational.
- Documentation is updated to reflect the setup process and configurations made, including the process for running a subnet locally for staging as per the [[Running on Staging](https://github.com/opentensor/bittensor-subnet-template/blob/main/docs/running_on_staging.md)](https://github.com/opentensor/bittensor-subnet-template/blob/main/docs/running_on_staging.md) documentation.

### Resources:

- [[Bittensor Running on Staging Guide](https://github.com/opentensor/bittensor-subnet-template/blob/main/docs/running_on_staging.md)](https://github.com/opentensor/bittensor-subnet-template/blob/main/docs/running_on_staging.md)
- [[AWS Documentation](https://docs.aws.amazon.com/)](https://docs.aws.amazon.com/)
- [[Rust Programming Language](https://www.rust-lang.org/)](https://www.rust-lang.org/)

### Notes:

- Ensure that all AWS resources are tagged appropriately for cost tracking.
- The staging environment setup should mimic the production environment as closely as possible to ensure that any tests conducted are representative of a live deployment.
